spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/cs?serverTimezone=Asia/Seoul
        username: bj
        password: 1234
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB

server:
    servlet:
        encoding:
            charset: UTF-8

    tomcat:
        uri-encoding: UTF-8

    port: 8081